### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by PlacidFox** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#13] opened 2023-02-04 10:40 UTC
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-6-pathway-2%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-persisting-data-room#5

**Specify the language of the codelab if it is not English:**
French

**In which task and step of the codelab can this issue be found?**
6 - Créer le DAO

**Describe the problem**
request must be : @Query("SELECT * from items WHERE id = :id")
not @Query("SELECT * from item WHERE id = :id")

because tableName is items and not item

**Steps to reproduce?**

**Versions**

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-04-06 21:20
Duplicate of #8, #6.

**Closed** 2023-04-22 22:16 UTC
