### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by GabrielGomezGG** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#17] opened 2023-02-15 13:22 UTC
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room?authuser=1&hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-6-pathway-2%3Fauthuser%3D1%26hl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-persisting-data-room#5

**Specify the language of the codelab if it is not English:**
Español

**In which task and step of the codelab can this issue be found?**
6. Crea el elemento DAO

**Describe the problem**
En las @Query se llama a la tabla "item" en minuscula. Cuando en el entity lo nombramos como "items".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-04-06 21:19
Duplicate of #13, #8, #6.

**Comment by osuleymanova** [comment] 2023-07-25 22:08
Hello @GabrielGomezGG,

Thank you for reaching out to us. It is fixed and published.

**Closed by osuleymanova** 2023-07-25 22:08 UTC
