### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by lixoten** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#8] opened 2023-01-26 07:52 UTC
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-6-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-persisting-data-room#4

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
Step 5
5. Create an item Entity

**Describe the problem**
in item 2. it says to set the items as in plural.. it should be singular as in "item" NOT "items" THIS IS VERY MISLEADING.. SEE Screenshot images
"Above the Item class declaration, annotate the data class with @Entity. Use the tableName argument to set the **_items_** as the SQLite table name."

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/52259786/214783493-a72ccd22-d539-49fa-8aa5-37771ca81c81.png)

**Comment by osuleymanova** [comment] 2023-04-06 21:20
Duplicate of #6

**Comment by osuleymanova** [comment] 2023-07-25 22:09
Hello @lixoten,

Thank you for reaching out to us. It is fixed and published.

**Closed by osuleymanova** 2023-07-25 22:09 UTC
