### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by lyay** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#20] opened 2023-03-15 20:54 UTC
[**URL of codelab:**]
(https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room#5)

**Specify the language of the codelab if it is not English:**
SQL

**In which task and step of the codelab can this issue be found?**
[6. Create the item DAO](https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room#5) 

**Describe the problem**
Error in SQL query.
Wrong table name in @Query("SELECT * from item WHERE id = :id")
Right string  @Query("SELECT * from items WHERE id = :id")

**Comment by osuleymanova** [comment] 2023-04-06 21:14
Duplicate of #17

**Comment by osuleymanova** [comment] 2023-07-25 22:08
Hello @lyay,

Thank you for reaching out to us. It is fixed and published.

**Closed by osuleymanova** 2023-07-25 22:08 UTC
